### ISSUE TITLE
ELM327 with USB cable

### ISSUE THREAD

**Issue by aster94** [PowerBroker2/ELMduino#10]
Hi!

I would guess that your library works using bluetooth commands, isn't it?

Have you ever saw this EML327 adapter?
![image](https://user-images.githubusercontent.com/21184718/77857037-9ba17080-71fb-11ea-9bb5-348215d3648c.png)
I would be curios to know if it the same command you send via BT works the same via Serial, do you have any idea?

**Comment by PowerBroker2** [comment]
The commands would be the same, but you would need a USB host interface to drive the device. You can't plug one of those directly to Serial, if that makes sense.

**Comment by aster94** [comment]
actually i read that these adapter uses a CH340 so I was thinking about getting rid of the CH340 and use directly the TTL signal with your library.

I know i could use BT but I would like the fastest communication possible

BTW a few years ago I wrote a library that uses the [keyword protocol](https://github.com/aster94/Keyword-Protocol-2000) but soon i will get a new motorbike that uses the can bus so your library would be perfect

**Comment by PowerBroker2** [comment]
If you can access the TTL UART lines  of the ELM327 directly, the library should work perfectly for you

**Comment by PowerBroker2** [comment]
I'm going to close this for now, but if you have more issues with this you can reopen it.
