### ISSUE TITLE
Error compilling

### ISSUE THREAD

**Issue by AekPu** [PowerBroker2/ELMduino#109]
Arduino: 1.8.19 (Windows 10), Board: "Arduino Uno"

C:\Users\Aekkarad\Documents\Arduino\libraries\ELMDuino-3.0.0\src\ELMduino.cpp: In member function 'float ELM327::batteryVoltage()':

C:\Users\Aekkarad\Documents\Arduino\libraries\ELMDuino-3.0.0\src\ELMduino.cpp:2632:11: error: 'strtof' was not declared in this scope

    return strtof(payload, NULL);

           ^~~~~~

C:\Users\Aekkarad\Documents\Arduino\libraries\ELMDuino-3.0.0\src\ELMduino.cpp:2632:11: note: suggested alternative: 'strtok'

    return strtof(payload, NULL);

           ^~~~~~

           strtok

exit status 1

Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by PowerBroker2** [comment]
What happens if you replace all `strtof()` calls to `strtod()`? Does the error go away?

**Comment by PowerBroker2** [comment]
No, if you go into ELMduino.cpp and replace all instances of `strtof` to `(float)strtod`, do you still get a compile time error?

**Comment by AekPu** [comment]
It complied and No error

ในวันที่ พฤ. 27 ม.ค. 2022 เวลา 00:03 PB2 ***@***.***>
เขียนว่า:

**Comment by PowerBroker2** [comment]
Fixed in [3.0.1](https://github.com/PowerBroker2/ELMduino/releases/tag/3.0.1)

**Comment by AekPu** [comment]
for use , i must setting HC05 in AT MODE right?

ในวันที่ พฤ. 27 ม.ค. 2022 เวลา 12:41 PB2 ***@***.***>
เขียนว่า:
