### ISSUE TITLE
Use with Arduino 33 iot and ArduinoBLE

### ISSUE THREAD

**Issue by sd4solutions** [PowerBroker2/ELMduino#112]
Hello @PowerBroker2, thanks for your work.
I need to use it with my arduino 33 iot, but i see you use serial to connect via bluetooth.
ArduinoBLE lib has BLEDevice object to pair devices: how i can use it with your lib?

Thanks in advance.

**Comment by PowerBroker2** [comment]
This library currently does not support BLE. I'm considering supporting it, but not anytime soon (if ever). If you or someone else wants to see what it takes for this lib to support BLE and submits a PR, I will be happy to merge.
