### ISSUE TITLE
ESP32 - Timeout detected with overflow of 0ms

### ISSUE THREAD

**Issue by Pilonetto** [PowerBroker2/ELMduino#113]
Hello, I have an ELM327 of the following [model](https://www.amazon.com.br/Bluethooth-Scanner-Diagn%C3%B3stico-Automotivo-ELM327/dp/B00QUL6U8Y/ref=pd_sbs_2/144-8940329-4890754?pd_rd_w=qoVO9&pf_rd_p=cd87be50-d82a-47b7- ba72-5e5ad9968f57&pf_rd_r=9XBYKF02TNCRPHKEXB8Z&pd_rd_r=9603499c-515b-4817-9737-5b1a5af90047&pd_rd_wg=TuH5M&pd_rd_i=B00QUL6U8Y&psc=1)

I use an ESP32 WROOM and the example provided [here](https://github.com/PowerBroker2/ELMduino/tree/master/examples/ESP32_Bluetooth_Serial).

Despite being plugged in and with the ignition on, I always get the message `Timeout detected with overflow of 0ms`
[testeesp.txt](https://github.com/PowerBroker2/ELMduino/files/7978517/testeesp.txt)

![esp32-test](https://user-images.githubusercontent.com/18617113/151971162-b37d350f-73ce-4f51-aee9-841b91b231c4.png)

Full log attached.

**Comment by qqm55** [comment]
I'm also having this same issue, can upload sections of my code, am on mobile atm. But my code is based off RPM BT SERIAL sketch. Any solutions to this issue?
