### ISSUE TITLE
Engine intake temperature not calculated correctly

### ISSUE THREAD

**Issue by CamilV** [PowerBroker2/ELMduino#116]
**Describe the bug**
The function call for processPID is missing a parameter and -40 is taken as the scale factor, not bias factor

**To Reproduce**
Simply call the intakeAirTemp function and monitor the response. For a response of 410F2B, the calculated temp is -1720, not 3. 

**Expected behavior**
Convert 0x2B into 43 decimal and substract 40, rather than multiply by -40

**Equipment**
Cheap ELM327 with PIC controller, Arduino nano with HC05

**Comment by PowerBroker2** [comment]
Should be fixed in release [3.0.2](https://github.com/PowerBroker2/ELMduino/releases/tag/3.0.2), thank you!
