### ISSUE TITLE
Toyota Yaris Multi PID

### ISSUE THREAD

**Issue by kondorcl** [PowerBroker2/ELMduino#119]
Hello Power Broker2. thanks very much for share ur ELMduino project.

I have an Toyota Yaris 2008 and test multi PID query with ELMduino V2.5.0 and ELM327 Bluetooh, ESP32 and SH1106 display. I can't get fuelLevel and batteryVolts; but with library V3.0.1 I can read (only one rquest) fuelLevel = 4.
Please could u check the attach files?

You cooperation in this matter will be appreciated. 
[esp32_obd2_ble.zip](https://github.com/PowerBroker2/ELMduino/files/8398457/esp32_obd2_ble.zip)

**Comment by PowerBroker2** [comment]
Please see the library examples and the cpp file for complete documentation. Also, you need to check the `myELM327.status` for each and every PID query.
