### ISSUE TITLE
Reading values at specified intervals - custom PID.

### ISSUE THREAD

**Issue by maciekelga** [PowerBroker2/ELMduino#122]
Hi,

I have a program as in attachment. Is reading two custom PIDs: one is for distance from last regeneration - I will add some code for calculation later. Second is for check if regeneration is on or off.

For me is enought if those readings are done in every 3-5 second. How I can implement this to get this reading, let`s say every 5 second?

In additional in attachment is a log from serial monitor. It looks that from time to time it gives 0 instead of values (B,C,D), readings B=1, C=98, D=85 are correct. How to solve it?

[log.txt](https://github.com/PowerBroker2/ELMduino/files/8455396/log.txt)

[program.zip](https://github.com/PowerBroker2/ELMduino/files/8455384/program.zip)

**Comment by PowerBroker2** [comment]
This seems like an issue with your project, not the library - please use the [Arduino forum](https://forum.arduino.cc/) for such questions
