### ISSUE TITLE
some of the data cannot be read from the OBD [HELP]

### ISSUE THREAD

**Issue by juliusfelix12** [PowerBroker2/ELMduino#127]
hello @PowerBroker2 first of all i wanna say thankyou for making this awesome library! it's very helpful to connect and query between the microcontroller and the vehicle's OBD port, really appreciate it!

this is my first project i made using ELMduino (my setup: ESP32, ELM327 v1.5, i2c LCD 20x4), and it works like a charm :) but i have a few questions.
![obd](https://user-images.githubusercontent.com/71480360/172054823-c4fd98f1-063a-4aaf-ab01-b8b9045ff156.jpg)

question:
1. i was trying to query the oilTemp() and fuelLevel() but ended up not getting any data, i saw from the serial monitor that the OBD sent NO DATA message, does that mean my car doesn't have a sensor to measure that value OR is there a specific code to query each car?
<img width="1440" alt="Screen Shot 2022-06-05 at 4 13 11 PM 2" src="https://user-images.githubusercontent.com/71480360/172054909-6a02e362-68a0-4ca0-b99b-f80cfc9d6572.png">
<img width="1440" alt="Screen Shot 2022-06-05 at 4 15 14 PM" src="https://user-images.githubusercontent.com/71480360/172055562-bf23d76b-69f0-4a11-93ac-debc77ee92f8.png">

2. i've used the batteryVoltage() function to get the voltage value from my car's battery, but i'm hoping to get an accurate value (with one digit after the comma), i know it's very possible because the OBD responds with 12.5v but the printable values is only 12v, i wonder what should i do to get 12.5v value instead of 12v? i was trying to modify the elmduino.cpp and elmduino.h files but i haven't been able to solve the problem...
<img width="1440" alt="Screen Shot 2022-06-05 at 5 31 45 PM" src="https://user-images.githubusercontent.com/71480360/172055315-4ba95cd8-5b15-470f-a2a7-46d29d5fbcc5.png">

hope someone or @PowerBroker2 can help me to solve this problem, thanks in advance!

**Comment by PowerBroker2** [comment]
For the "NO DATA" part - yes, this means the data for this PID is unavailable from your car and you're more or less SOL. As for the battery voltage, you're typecasting the voltage float into an int, so it chops off the decimal and everything after.
