### ISSUE TITLE
ERROR 7 On ESP32 Wrover Board

### ISSUE THREAD

**Issue by vsaravind007** [PowerBroker2/ELMduino#13]
Arduino IDE Version: **1.8.5**
ELMduino Library Version: **2.0.11** (Latest at the time of opening this issue)
ESP32 Build Tools Version: **1.0.4** (Latest at the time of opening this issue)
ESP32 Board Used: **Wroom 32 ESP32 Dev Board**
ELM327 Module: Generic Bluetooth ELM327 

**Issue description**
Getting ERROR 7 on the serial console while running the ESP32_Bluetooth_Serial.io example, Used the file ESP32_Bluetooth_Serial.ino that came with the library, only changes were updating the Bluetooth name of the ELM327 module & commenting the following lines since LED_BUILTIN is not defined for this particular ESP32 board:

```
pinMode(LED_BUILTIN, OUTPUT);
digitalWrite(LED_BUILTIN, HIGH);
```

No issues with compilation or connection with the ELM327 module, ESP32 is connecting fine with the module quickly  its a generic known working device, Torque works fine.

Tried sending AT commands using the minimal example & it worked fine, module responds back with values for AT commands. 

Attaching the screenshot of the serial monitor:
![aa](https://user-images.githubusercontent.com/1938082/78455090-e7e82700-76b9-11ea-9af8-0bc778fb59be.png)

**Comment by PowerBroker2** [comment]
I'll fix the example code so that the compilation error isn't a problem anymore. Curious, are you testing with the car on and running?

**Comment by vsaravind007** [comment]
Yes, the car is running, its a Skoda Octavia MK2 TDI. Does it have something to do with the OBD2 protocol?

**Comment by PowerBroker2** [comment]
It might actually have something to do with the OBD interface if you're car was made on or before 2008. When was your car made?

**Comment by vsaravind007** [comment]
Its a 2008 model, Arduino with a CANBus Shield works fine and responds to all PIDs correctly.

**Comment by PowerBroker2** [comment]
I found a bug in the code and applied a fix in version 2.0.12. Try testing the new ESP32 Bluetooth Serial example. If it still doesn't work for you, try the ESP32 test sketch and post what happens when you send the following ELM327 commands:

```C++
AT E0 //Echo off
AT S0 //Spaces off
AT SP0 //Mode --> Automatic
010C //Query RPM
```

**Comment by vsaravind007** [comment]
Hi @PowerBroker2, thanks for the quick update, I'll check with the latest version & report back.

**Comment by PowerBroker2** [comment]
Did you get it to work?

**Comment by vsaravind007** [comment]
Apologies for the later response, couldn't test it yet. Will be testing it today or tomorrow, I'll make sure to update here.

**Comment by pascaltippelt** [comment]
Hi!
I am having the same issue. I am using a ESP32 (glued on a TTGO T4, but it is a box standart ESP32). When I try to connect over BT to my OBD-Stick (verified working with Android Smartphone + Torque) I only get "Error 7":

Outpup with my own program:

![WhatsApp Image 2020-04-19 at 15 29 26](https://user-images.githubusercontent.com/2066297/79689234-b2177680-8253-11ea-9551-6d02916f417e.jpeg)

Output with you ESP32 test program

![WhatsApp Image 2020-04-19 at 15 35 28(1)](https://user-images.githubusercontent.com/2066297/79689237-b348a380-8253-11ea-8031-4e2041ba6e52.jpeg)

But as you can see it works with Torque

![WhatsApp Image 2020-04-19 at 15 35 28](https://user-images.githubusercontent.com/2066297/79689240-b479d080-8253-11ea-972d-2549b61e6097.jpeg)

I use a 2000 smart car wich uses the ISO14230-4 KWP fast protocoll.

**Comment by PowerBroker2** [comment]
@pascaltippelt Please create a new issue instead of hijacking this one. In your new issue, please make sure to post your entire sketch properly formatted in addition to the screenshots you have here.

**Comment by vsaravind007** [comment]
@PowerBroker2 My issue has been resolved, thanks for the library and the efforts! I'm closing the ticket :)

**Comment by PowerBroker2** [comment]
@vsaravind007 Can I ask how you solved it?
