### ISSUE TITLE
how to read and erase codes?

### ISSUE THREAD

**Issue by FabioSierra** [PowerBroker2/ELMduino#132]
Thank you so much for such an impressive creation and for sharing it with everyone.

That's the first thing, my question and sorry if it's too silly (I'm new to arduino) is how I read and delete error codes? I would like to see an example code of each case to be able to implement what I am doing.

Thank you very much again and I hope you have a lot of health and life!

**Comment by PowerBroker2** [comment]
I never messed with error codes, but from what I understand, they're usually proprietary codes/responses. The first thing to do is see what service and pid numbers correspond to the error codes you're interested and figure out how the responses are formatted. Perhaps car forums would be of more help
