### ISSUE TITLE
ESP32-S3 BLE Support?

### ISSUE THREAD

**Issue by PlastiBots** [PowerBroker2/ELMduino#135]
Hi. I found that ESP32-S3's don't support Bluetooth Serial.  Any chance of getting this working using BLE?  Thx.

**Comment by PowerBroker2** [comment]
I'm not familiar with BLE. If you (or anyone else) knows how to interface with ELM327s over BLE, I would be happy to roll those functions into the lib. Otherwise, I don't know how to do it.

**Comment by PlastiBots** [comment]
Ok thx.

**Comment by patfelst** [comment]
This guy has implented a BLE interface for ELM, he uses it for a gear shift light. The code is spread across many source files, so looks pretty involved to separate out the bits you'd need for this library.
https://github.com/janmannsbart23/OBDShiftIndicator

**Comment by PlastiBots** [comment]
Thx. Will have a look.  I’m working with a VGate iCar Pro ODBII reader that’s BLE.  Was able to poll via an ESP32 using BluetoothSerial, but I need to use an ESP32-s3 which does not support BT over serial, so trying to figure out how to talk to the VGate using BLE and am green with my understanding of Services and Characteristics and not even sure if I can parse the VGate that way…
