### ISSUE TITLE
I found the VEHICLE_SPEED is no more than 127 km/h

### ISSUE THREAD

**Issue by yongwn** [PowerBroker2/ELMduino#136]
I test this lib in my car, it works ok.

But if the speed > 127 km/h , it will show a wrong speed.

I check the code 
ELMduino.cpp
```
int32_t ELM327::kph()
{
	return (int32_t)processPID(SERVICE_01, VEHICLE_SPEED, 1, 1);
}
```
I think it may something wrong when convert byte to int32_t

**Comment by PowerBroker2** [comment]
I can't find any issues with the code. The int32_t type cast is not a problem since the max kph value over OBD2 is 255. The issue is most likely with your ELM327 or car diagnostics computer.

**Comment by yongwn** [comment]
i use a simulator,it works ok,it may elm327's problem
