### ISSUE TITLE
how to set the ELM_PORT with ble to ESP C3?

### ISSUE THREAD

**Issue by saagcs** [PowerBroker2/ELMduino#138]
In serial bluetooth the code was used like this:

```
BluetoothSerial SerialBT;
#define ELM_PORT SerialBT
#define DEBUG_PORT Serial
```

But with BLE, how can I set the ELM_PORT?

**Comment by PowerBroker2** [comment]
Right now BLE is unsupported since I don't know how to use it. Other threads here have attempted to point me to BLE examples, but they're all super confusing. I'm hoping someone with more BLE experience will submit a PR to add BLE support...

**Comment by saagcs** [comment]
ok very thanks for answer :)
