### ISSUE TITLE
Fastest and smoothest way of communication

### ISSUE THREAD

**Issue by Arashinof** [PowerBroker2/ELMduino#139]
Hi im planing to use elm327 + esp8266 + oled display to make a digital speedometer with rpm value and lighting 
Every elm327 has rx/tx pins and some modules send the data over usb, some send over wifi and some send over Bluetooth 

So my question is: which is the fastest? I mean when you receive more data the display numbers will change more and that lead to have a more smooth and less laggy display right? 
Should i go with wifi or Bluetooth? Or wire the rx/tx to another esp8266 and send the data to the esp8266 that drives the oled display? 
Thanks

**Comment by PowerBroker2** [comment]
I have my own personal HUD (which is the reason I developed this lib in the first place) that uses a bluetooth ELM327, HC-05, and Teensy 4.1. It works exceptionally well and is quite responsive. I'd suggest using the same setup if possible.

**Comment by Arashinof** [comment]
Thanks
