### ISSUE TITLE
Slow data refresh rate

### ISSUE THREAD

**Issue by DanteCecchetti** [PowerBroker2/ELMduino#155]
Hello, I was just able to connect the obd to my arduino through a hc-05 module.
However, something strange happened to me, I don't know if it has to do with the ECU model of my car or with the ELMduino library. It turns out that I used the example that you posted on your github to read the RPM of the engine, but the value of the data was given to me with a long delay, more or less, 4 or 5 seconds. Is there any way to make the data transfer faster?
I clarify that mostly what the arduino serial port showed me was the NO DATA message and sporadically the rpm value appeared.

**Comment by PowerBroker2** [comment]
The `NO DATA` part makes me think the issue is with your car. You'll probably find better help on either the Arduino or car related forums
