### ISSUE TITLE
incompatibility between libraries

### ISSUE THREAD

**Issue by DanteCecchetti** [PowerBroker2/ELMduino#161]
Hello, I was trying to program with your library to make a kind of clock in the vehicle that has several profiles, where each profile shows different data. The problem occurs when I want to run simultaneously both your library and the adafruits library called, Adafruit_SSD1306 and the Adafruit_GFX.h library, it happens that the oled screen that I am using does not refresh the screen. I wanted to ask you if you know of any library that allows you to use screens of this type and that are compatible with your library. I've attached my code so you can see what I've been trying to test.

#include "ELMduino.h"
#include <SoftwareSerial.h>
#include <Wire.h>			// libreria para bus I2C
#include <Adafruit_GFX.h>		// libreria para pantallas graficas
#include <Adafruit_SSD1306.h>		// libreria para controlador SSD1306 
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);

SoftwareSerial mySerial(2, 3); // RX, TX
#define ELM_PORT mySerial
ELM327 myELM327;

uint32_t rpm = 0;

void setup()
{
  display.begin(SSD1306_SWITCHCAPVCC, 0x3C); //init the oled screen
  display.clearDisplay();//clear the oled screen

#if LED_BUILTIN
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
#endif

  Serial.begin(115200);
  ELM_PORT.begin(115200);

  Serial.println("Attempting to connect to ELM327...");
  if (!myELM327.begin(ELM_PORT, true, 2000))
  {
    Serial.println("Couldn't connect to OBD scanner");
    
    while (1);
  }

  Serial.println("Connected to ELM327");
  display.clearDisplay();
  display.setTextColor(WHITE);
  display.setCursor(0,0);
  display.setTextSize(2);  
  display.print("Connected to ELM327");		
  display.display(); 
}

void loop()
{
  float tempRPM = myELM327.rpm();

  if (myELM327.nb_rx_state == ELM_SUCCESS)
  {
    rpm = (uint32_t)tempRPM;
    Serial.print("RPM: "); Serial.println(rpm);
  }
  else if (myELM327.nb_rx_state != ELM_GETTING_MSG)
    myELM327.printError();
}

**Comment by PowerBroker2** [comment]
This is a question for [the Arduino forum](https://forum.arduino.cc/)
