### ISSUE TITLE
Problem getting data from the ELM327

### ISSUE THREAD

**Issue by miguelgarcia42** [PowerBroker2/ELMduino#163]
Hey guys , im getting always the same error using ELMduino library , right now im using OBDsim to simulate the elm327 on my PC via bluetooth  (i get the exact same response when using it in my car with a standard ELM327 bluetooth adapter) .
I can make it work with the softwareSerial library but im having trouble converting the rpm value from hexadecimal to decimal , thats why im trying ELMduino.

The code im using:

```
#include <SoftwareSerial.h>
#include "ELMduino.h"


SoftwareSerial mySerial(8, 9); // RX, TX
ELM327 myELM327;


uint32_t rpm = 0;


void setup()
{
  Serial.begin(115200);
  mySerial.begin(115200);
  myELM327.begin(mySerial, true, 2000);
}


void loop()
{
  float tempRPM = myELM327.rpm();

  if (myELM327.nb_rx_state == ELM_SUCCESS)
  {
    rpm = (uint32_t)tempRPM;
    Serial.print("RPM: "); Serial.println(rpm);
  }
  else if (myELM327.nb_rx_state != ELM_GETTING_MSG)
    myELM327.printError();
}
```

The serial monitor loops this and the rpm is always 884:
![Serial Monitor Log](https://user-images.githubusercontent.com/105513478/228883492-dc3d798e-aa39-478e-a7e6-c24f46f9dc77.png)

This is the OBDSim log , it is getting the commands to reset and the queries.

![OBDSim CMD log](https://user-images.githubusercontent.com/105513478/228883666-455a6b68-7f8a-438a-9012-593b7bd7af2d.png)

Hope someone can help me fix this , thanks :)

**Comment by PowerBroker2** [comment]
If the query is `010C1`, then the response header should be `410C1`. However, it seems the sim is sending a response header of  `410C0` for some reason. This means ELMduino will not recognize the header and eventually time out.

**Comment by miguelgarcia42** [comment]
> If the query is `010C1`, then the response header should be `410C1`. However, it seems the sim is sending a response header of `410C0` for some reason. This means ELMduino will not recognize the header and eventually time out.

Any sugestion on how i can fix it? I get the same error with the elm327 plugged to my car

**Comment by PowerBroker2** [comment]
Seems like both your car and sim are screwed up, not sure how to fix that. Perhaps you could jerry-rig the lib src files to work around the issue.

What is your car's make/model/year?

**Comment by miguelgarcia42** [comment]
> Seems like both your car and sim are screwed up, not sure how to fix that. Perhaps you could jerry-rig the lib src files to work around the issue.
> 
> What is your car's make/model/year?

Oh ok :/ i will try to find a way to fix it , it is a 2017 honda civic hatchback

**Comment by PowerBroker2** [comment]
Interesting, I was expecting a pre-2008 car since it doesn't seem to be adhering to the OBD2 standard

**Comment by vladislav-n-dario** [comment]
Hi @PowerBroker2 ! Currently having timeout stuff with my Civic 8th gen Hatchback 2007, can you please give more info on those issues you've mentioned with pre-2008 Civics?
