### ISSUE TITLE
ELMduino with meatPi WiCan device

### ISSUE THREAD

**Issue by jjharlow** [PowerBroker2/ELMduino#164]
Curious if anyone has tried this with with the meatPi WiCAN device. I picked one up and tried it in ELM327 mode with a wifi connection (It also supports BLE but I don't think BLE devices work with ELMduino at least in my testing).

https://github.com/meatpiHQ/wican-fw

I can connect to the OBD device but it doesn't seem to work. Not sure if that's related to this ELM327v1.3a, I have worked with other OBDII devices with ELMduino but only using Bluetooth and I believe they were all ELM version 1.5 devices.

Thought I would try this device as it has a number of other cool features (aside from being based on the ESP32) and has a built-in sleep mode and battery saver. 

15:31:46.856 -> Connected to Wifi
15:31:46.856 -> IP address: 
15:31:46.856 -> 192.168.80.2
15:31:46.856 -> connected
15:31:46.856 -> Clearing input serial buffer
15:31:46.856 -> Sending the following command/query: AT D
15:31:47.212 -> 	Received char: O
15:31:47.212 -> 	Received char: K
15:31:47.212 -> 	Received char: \r
15:31:47.212 -> 	Received char: \n
15:31:47.386 -> 	Received char: \r
15:31:47.386 -> 	Received char: >
15:31:47.386 -> Delimiter found.
15:31:47.386 -> All chars received: OK
15:31:47.478 -> Clearing input serial buffer
15:31:47.478 -> Sending the following command/query: AT Z
15:31:47.834 -> 	Received char: E
15:31:47.834 -> 	Received char: L
15:31:47.834 -> 	Received char: M
15:31:47.834 -> 	Received char: 3
15:31:47.834 -> 	Received char: 2
15:31:47.834 -> 	Received char: 7
15:31:47.834 -> 	Received char: _
15:31:47.834 -> 	Received char: v
15:31:47.834 -> 	Received char: 1
15:31:47.834 -> 	Received char: .
15:31:47.834 -> 	Received char: 3
15:31:47.834 -> 	Received char: a
15:31:47.834 -> 	Received char: \r
15:31:47.834 -> 	Received char: \n
15:31:47.880 -> 	Received char: \r
15:31:47.880 -> 	Received char: >
15:31:47.880 -> Delimiter found.
15:31:47.880 -> All chars received: ELM327v1.3a
15:31:47.975 -> Clearing input serial buffer
15:31:47.975 -> Sending the following command/query: AT E0
15:31:48.240 -> 	Received char: O
15:31:48.240 -> 	Received char: K
15:31:48.240 -> 	Received char: \r
15:31:48.240 -> 	Received char: \n
15:31:48.382 -> 	Received char: \r
15:31:48.382 -> 	Received char: >
15:31:48.382 -> Delimiter found.
15:31:48.382 -> All chars received: OK
15:31:48.475 -> Clearing input serial buffer
15:31:48.475 -> Sending the following command/query: AT S0
15:31:48.661 -> 	Received char: O
15:31:48.661 -> 	Received char: K
15:31:48.661 -> 	Received char: \r
15:31:48.661 -> 	Received char: \n
15:31:48.878 -> 	Received char: \r
15:31:48.878 -> 	Received char: >
15:31:48.878 -> Delimiter found.
15:31:48.878 -> All chars received: OK
15:31:48.971 -> Clearing input serial buffer
15:31:48.971 -> Sending the following command/query: AT AL
15:31:49.249 -> 	Received char: ?
15:31:49.249 -> 	Received char: \r
15:31:49.249 -> 	Received char: \n
15:31:49.394 -> 	Received char: \r
15:31:49.394 -> 	Received char: >
15:31:49.394 -> Delimiter found.
15:31:49.394 -> All chars received: 
15:31:49.472 -> Clearing input serial buffer
15:31:49.472 -> Sending the following command/query: AT ST 00
15:31:49.658 -> 	Received char: O
15:31:49.658 -> 	Received char: K
15:31:49.658 -> 	Received char: \r
15:31:49.658 -> 	Received char: \n
15:31:49.892 -> 	Received char: \r
15:31:49.892 -> 	Received char: >
15:31:49.892 -> Delimiter found.
15:31:49.892 -> All chars received: OK
15:31:49.985 -> Clearing input serial buffer
15:31:49.985 -> Sending the following command/query: AT TP A0
15:31:50.296 -> 	Received char: ?
15:31:50.296 -> 	Received char: \r
15:31:50.296 -> 	Received char: \n
15:31:50.379 -> 	Received char: \r
15:31:50.379 -> 	Received char: >
15:31:50.379 -> Delimiter found.
15:31:50.379 -> All chars received: 
15:31:50.379 -> Setting protocol via AT TP A%c did not work - trying via AT SP %c
15:31:50.379 -> Clearing input serial buffer
15:31:50.379 -> Sending the following command/query: AT SP 0
15:31:50.690 -> 	Received char: O
15:31:50.690 -> 	Received char: K
15:31:50.690 -> 	Received char: \r
15:31:50.690 -> 	Received char: \n
15:31:50.891 -> 	Received char: \r
15:31:50.891 -> 	Received char: >
15:31:50.891 -> Delimiter found.
15:31:50.891 -> All chars received: OK
15:31:50.891 -> Setting protocol via AT SP %c did not work
15:31:50.891 -> Service: 1
15:31:50.891 -> PID: 12
15:31:50.891 -> Normal length query detected
15:31:50.891 -> Query string: 010C1
15:31:50.891 -> Clearing input serial buffer
15:31:50.891 -> Sending the following command/query: 010C1
15:31:51.281 -> 	Received char: B
15:31:51.281 -> 	Received char: U
15:31:51.281 -> 	Received char: S
15:31:51.281 -> 	Received char: _
15:31:51.313 -> 	Received char: I
15:31:51.313 -> 	Received char: N
15:31:51.313 -> 	Received char: I
15:31:51.313 -> 	Received char: T
15:31:51.313 -> 	Received char: :
15:31:51.313 -> 	Received char: _
15:31:51.313 -> 	Received char: .
15:31:51.313 -> 	Received char: .
15:31:51.313 -> 	Received char: .
15:31:51.313 -> 	Received char: E
15:31:51.313 -> 	Received char: R
15:31:51.313 -> 	Received char: R
15:31:51.313 -> 	Received char: O
15:31:51.313 -> 	Received char: R
15:31:51.313 -> 	Received char: \r
15:31:51.313 -> 	Received char: \r
15:31:51.313 -> 	Received char: >
15:31:51.358 -> Delimiter found.
15:31:51.358 -> All chars received: BUSINIT:...ERROR
15:31:51.358 -> ELM responded with "ERROR"
15:31:51.358 -> Received: BUSINIT:...ERROR
15:31:51.358 -> ERROR: ELM_GENERAL_ERROR
15:31:51.429 -> Service: 1
15:31:51.429 -> PID: 12
15:31:51.429 -> Normal length query detected
15:31:51.429 -> Query string: 010C1
15:31:51.429 -> Clearing input serial buffer
15:31:51.429 -> Sending the following command/query: 010C1
15:31:51.722 -> 	Received char: B
15:31:51.722 -> 	Received char: U
15:31:51.722 -> 	Received char: S
15:31:51.722 -> 	Received char: _
15:31:51.722 -> 	Received char: I
15:31:51.722 -> 	Received char: N
15:31:51.722 -> 	Received char: I
15:31:51.722 -> 	Received char: T
15:31:51.722 -> 	Received char: :
15:31:51.722 -> 	Received char: _
15:31:51.722 -> 	Received char: .
15:31:51.722 -> 	Received char: .
15:31:51.722 -> 	Received char: .
15:31:51.722 -> 	Received char: E
15:31:51.722 -> 	Received char: R
15:31:51.722 -> 	Received char: R
15:31:51.722 -> 	Received char: O
15:31:51.722 -> 	Received char: R
15:31:51.722 -> 	Received char: \r
15:31:51.722 -> 	Received char: \r
15:31:51.722 -> 	Received char: >
5:31:51.764 -> Delimiter found.
15:31:51.764 -> All chars received: BUSINIT:...ERROR
15:31:51.764 -> ELM responded with "ERROR"
15:31:51.764 -> Received: BUSINIT:...ERROR
15:31:51.764 -> ERROR: ELM_GENERAL_ERROR
15:31:51.855 -> Service: 1
15:31:51.855 -> PID: 12
15:31:51.855 -> Normal length query detected
15:31:51.855 -> Query string: 010C1
15:31:51.855 -> Clearing input serial buffer
15:31:51.855 -> Sending the following command/query: 010C1
15:31:51.887 -> 	Received char: B
15:31:51.887 -> 	Received char: U
15:31:51.887 -> 	Received char: S
15:31:51.887 -> 	Received char: _
15:31:51.887 -> 	Received char: I
15:31:51.887 -> 	Received char: N
15:31:51.887 -> 	Received char: I
15:31:51.887 -> 	Received char: T
15:31:51.887 -> 	Received char: :
15:31:51.887 -> 	Received char: _
15:31:51.887 -> 	Received char: .
15:31:51.887 -> 	Received char: .
15:31:51.887 -> 	Received char: .
15:31:51.887 -> 	Received char: E
15:31:51.887 -> 	Received char: R
15:31:51.887 -> 	Received char: R
15:31:51.887 -> 	Received char: O
15:31:51.887 -> 	Received char: R
15:31:51.887 -> 	Received char: \r
15:31:51.887 -> 	Received char: \r
15:31:51.887 -> 	Received char: >
15:31:51.933 -> Delimiter found.
15:31:51.933 -> All chars received: BUSINIT:...ERROR
15:31:51.933 -> ELM responded with "ERROR"
15:31:51.933 -> Received: BUSINIT:...ERROR
15:31:51.933 -> ERROR: ELM_GENERAL_ERROR
15:31:52.027 -> Service: 1
15:31:52.027 -> PID: 12
15:31:52.027 -> Normal length query detected
15:31:52.027 -> Query string: 010C1
15:31:52.027 -> Clearing input serial buffer
15:31:52.027 -> Sending the following command/query: 010C1

**Comment by PowerBroker2** [comment]
I've never seen a 'BUSINIT' error, but [according to this person, replacing the OBD2 reader worked](https://github.com/brendan-w/python-OBD/issues/187#issuecomment-629783877)
