### ISSUE TITLE
ESP32_test.ino does not work well

### ISSUE THREAD

**Issue by NickEsColR** [PowerBroker2/ELMduino#167]
I am trying to get some data from a car Renault Logan 2018. I buy an ELM327 adapter has the one in the following image
![image](https://user-images.githubusercontent.com/47890683/235324931-06c60191-dfff-452e-9668-0dd8a3ca60a7.png)
I already check if the adapter can read data using an app from play store, has can be seen in the following 2 images it shows some data and can be sure at least rpm is the real data.
<img src= "https://user-images.githubusercontent.com/47890683/235325078-03333a9f-e9b7-4655-be7f-d6e2f3c91b83.png" width="200" height="300">
<img src= "https://user-images.githubusercontent.com/47890683/235325082-180ce232-91ee-4611-a8d3-9374c41a1af7.png" width="200" height="300">
But when using an ESP32 and connect via bluetooth using MAC address with the example code and sent the AT commands it respond the following
![image](https://user-images.githubusercontent.com/47890683/235325134-71a37050-bc63-4f25-a228-2b30e6d13936.png)

I also check using a serial monitor app and it respond to some but not all AT commands. For example, the AT Z respond with ELM327v2.1, and ATSP0 ok. But some others like ATSP6, answer with question mark '?'
Also tried to send obd commands like 0100 or 010C but every one return '?'

I appreciate if anyone know why the some AT commands dont work and how i can get at least 1 data that is the requirement of my project.

**Comment by PowerBroker2** [comment]
What happens if you do CR and NL line ending?

**Comment by NickEsColR** [comment]
> What happens if you do CR and NL line ending?

![image](https://user-images.githubusercontent.com/47890683/235327357-3f307a28-fdc3-4ce0-b8e8-cda95d8aa215.png)
answer looks almost the same the only difference is this time doesn't repeat the command

**Comment by PowerBroker2** [comment]
Ok, in that case, go back to only CR line ending.

I'd say ensure no other bluetooth device is connected to the ELM327 at the same time. Also ensure your car is on and running. Lastly try all different bauds.

If none of these fix it, use a better OBD2 scanner.

**Comment by NickEsColR** [comment]
I got news, after trying every baud without success and currently in 19200 i decide to enter '>ATZ' instead of 'AT Z' and it succesfully answer. also want to add using space dont respond has expected
![image](https://user-images.githubusercontent.com/47890683/235375984-96166628-ac1b-4fa8-a00f-0b1d8d26cf4d.png)
I also try using the AT commands suggested in the test script and all respond OK, but using OBD pids still dont respond as you can see in the following image
![image](https://user-images.githubusercontent.com/47890683/235376141-28febba0-89db-4834-87cd-591fc68472b3.png)
I am curious if maybe exist more than one way to ask for them has the AT commands situation, also i would add that the app i previously use to verify data can be retrieve has 2 step connection, first connect to ELM327 and after connect to ECU.

**Comment by PowerBroker2** [comment]
Idk what your scanner is doing, I think you should use a better one
