### ISSUE TITLE
Service 22 PID's for GM LS PCM

### ISSUE THREAD

**Issue by blairhacche** [PowerBroker2/ELMduino#174]
I am attempting to retrieve Transmission Temp (0x1940) and Fuel level (0x1155) from a GM LS PCM. These requests work in the torque app and in HP tuner software however I have been unable to make them work using code and examples I have found online. From what I have found it appears that service 22 requests on this gm pcm require a different header on the requests, eg: PID 221940 (GM method 1), Equation: A-40, OBD Header: 7E2. My question is: Is there a way in elmduino to use a custom header like this on the request or is my only option to alter the request and response in the library myself?

**Comment by PowerBroker2** [comment]
I think this is possible, but you'll have to do some of the lower level implementation yourself. These functions would be a good place to start:

https://github.com/PowerBroker2/ELMduino/blob/eabbb1a2e8e82d8fed1b758c0d893bc46efbe171/src/ELMduino.h#L314-L316

There are documentation strings in the cpp files where these functions are defined.
