### ISSUE TITLE
Why does it take so long to connect?

### ISSUE THREAD

**Issue by edo44** [PowerBroker2/ELMduino#176]
Via bluetooth the esp takes 27 seconds to connect. Even if I specify the protocol in ELM327::begin() . Why is that?
Is the ELM327 maybe the cause?

**Comment by PowerBroker2** [comment]
No idea. Maybe try a different OBD2 scanner and/or arduino?

**Comment by edo44** [comment]
> No idea. Maybe try a different OBD2 scanner and/or arduino?

How long does it usually take to connect to you?


> Try connecting by BT MAC address instead of BT name. It is faster in my experience. There are plenty of closed issues that describe how to do this.

I'm already conecting using the MAC address of the device.

**Comment by patfelst** [comment]
I don't know then. Try compiling with verbose logging turned on, you'll be see the whole BT connection process, it may give some clues.

**Comment by edo44** [comment]
> I don't know then. Try compiling with verbose logging turned on, you'll be see the whole BT connection process, it may give some clues.

How do I activate the verbose logging?

**Comment by patfelst** [comment]
I only use PlatformIO and from there you set the log level using a build flag in the `platform.io` file as follows:
```c++
build_flags = 
  ; -DCORE_DEBUG_LEVEL=0 ; None
  ; -DCORE_DEBUG_LEVEL=1 ; Error
  ; -DCORE_DEBUG_LEVEL=2 ; Warn
  ; -DCORE_DEBUG_LEVEL=3 ; Info
  ; -DCORE_DEBUG_LEVEL=4 ; Debug
  -DCORE_DEBUG_LEVEL=5 ; Verbose
```
If you use Arduino IDE, I assume you can add this line to the top of your .ino file:
```c++
#define CORE_DEBUG_LEVEL 5 // Turn on verbose logging
```

**Comment by patfelst** [comment]
apparently you can set the log level from the Arduino IDE tools menu instead of using the #define method
![image](https://github.com/PowerBroker2/ELMduino/assets/11342773/02694fe6-5b88-4973-b666-dbe9f106a4f1)

**Comment by patfelst** [comment]
oh great, glad you found the problem!
