### ISSUE TITLE
BLE functionality ESP32-C3/S3

### ISSUE THREAD

**Issue by nellydocs** [PowerBroker2/ELMduino#181]
Hi everyone,

i have been searching for a script that supports BLE.
The standard Esp32 is not always available with some modules, 
like this one[https://de.aliexpress.comitem1005005764642600.html](url)

There is one giga brain who managed to utilize BLE to communicate with an elm327, his code is to complex for me.
[https://github.com/janmannsbart23/OBDShiftIndicator](url)

I tried using Wifi but as #52 mentions those things just dont work that well.

If i do not get BLE working in the next days i will try the following approach:

elm327 -> esp32 ->(using ESP-NOW) -> C3/S3 module

Any help is appreciated
Nelly

**Comment by PowerBroker2** [comment]
BLE is not supported
