### ISSUE TITLE
Vgate iCar Pro BLE 4.0 not getting data

### ISSUE THREAD

**Issue by themagicm** [PowerBroker2/ELMduino#183]
I'm using that BT dongle and am using BluetoothSerial and Elmduino.  I can connect to "Android-Vlink" but when I request RPM (and only RPM to test) I get ELM_TIMEOUT and ELM_STOPPED.

It does say "Connected to ELM" so I at least connect to it and can pull voltage which I am assuming is coming from what the dongle says it sees.

My previous question is not related to this module.  That other question I was using an old ELM327 from 6yrs ago and I thought, maybe its too old so I'll try this new one.

Clearing input serial buffer
Sending the following command/query: AT D
        Received char: A
        Received char: T
        Received char: _
        Received char: D
        Received char: \r
        Received char: \r
        Received char: O
        Received char: K
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: ATDOK
Clearing input serial buffer
Sending the following command/query: AT Z
        Received char: A
        Received char: T
        Received char: _
        Received char: Z
        Received char: \r
        Received char: \r
        Received char: \r
        Received char: E
        Received char: L
        Received char: M
        Received char: 3
        Received char: 2
        Received char: 7
        Received char: _
        Received char: v
        Received char: 2
        Received char: .
        Received char: 3
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: ATZELM327v2.3
Clearing input serial buffer
Sending the following command/query: AT E0
        Received char: A
        Received char: T
        Received char: _
        Received char: E
        Received char: 0
        Received char: \r
        Received char: O
        Received char: K
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: ATE0OK
Clearing input serial buffer
Sending the following command/query: AT S0
        Received char: O
        Received char: K
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: OK
Clearing input serial buffer
Sending the following command/query: AT AL
        Received char: O
        Received char: K
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: OK
Clearing input serial buffer
Sending the following command/query: AT ST 00
        Received char: O
        Received char: K
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: OK
Clearing input serial buffer
Sending the following command/query: AT TP A0
        Received char: O
        Received char: K
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: OK
Service: 1
PID: 5
Normal length query detected
Query string: 01051
Clearing input serial buffer
Sending the following command/query: 01051
        Received char: S
        Received char: E
        Received char: A
        Received char: R
        Received char: C
        Received char: H
        Received char: I
        Received char: N
        Received char: G
        Received char: .
        Received char: .
        Received char: .
        Received char: \r
Timeout detected with overflow of 0ms
Service: 1
PID: 47
Normal length query detected
Query string: 012F1
Clearing input serial buffer
Sending the following command/query: 012F1
        Received char: S
        Received char: T
        Received char: O
        Received char: P
        Received char: P
        Received char: E
        Received char: D
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: STOPPED
ELM responded with errror "STOPPED"
Service: 1
PID: 92
Normal length query detected
Query string: 015C1
Clearing input serial buffer
Sending the following command/query: 015C1
        Received char: S
        Received char: E
        Received char: A
        Received char: R
        Received char: C
        Received char: H
        Received char: I
        Received char: N
        Received char: G
        Received char: .
        Received char: .
        Received char: .
        Received char: \r
Timeout detected with overflow of 0ms
Clearing input serial buffer
Sending the following command/query: AT RV
        Received char: S
        Received char: T
        Received char: O
        Received char: P
        Received char: P
        Received char: E
        Received char: D
        Received char: \r
        Received char: \r
        Received char: >
Delimiter found.
All chars received: STOPPED
ELM responded with errror "STOPPED"

**Comment by themagicm** [comment]
Anyone used one of these before, successfully ?

**Comment by PowerBroker2** [comment]
The library does not support BLE scanners - not even sure how you got this far with your device. Perhaps try increasing the timeout value to an insane value like 10 seconds or so

**Comment by PiN0YChris** [comment]
This Scanner has 2 Bluetooth Connections/Modules "Android-Vlink" and "IOS-Vlink". Only the last one uses BLE. Just bought one because of this to try it an maybe tinkering with BLE later.

**Comment by jimwhitelaw** [comment]
@themagicm this looks like an issue I've encountered and am working through today. The quick and dirty fix is that given by @PowerBroker2 - bump up the timeout - I'm using 20 sec. and that works although you may not get data on your first query.  

The more robust fix is to modify the initializeELM() method to complete the protocol search when using AUTO protocol value. My fix looks like this: 

```c 
if ((String)protocol == "0")
{ //Auto search for protocol
	sprintf(command, TRY_PROT_H_AUTO_SEARCH, protocol); 
	if (sendCommand_Blocking(command) == ELM_SUCCESS)
	{ // Now we need to send OBD command to initiate protocol search
		if (sendCommand_Blocking("0100") == ELM_SUCCESS) 
		{// Not using the return value currently, but it gives a list of supported PIDs
		        connected = true;
			return connected;
		}
	}
}
else 
{
// set protocol
}

**Comment by PowerBroker2** [comment]
@jimwhitelaw 

Would you be cool with submitting a PR?

**Comment by jimwhitelaw** [comment]
Sure, I’ll be happy to. On Nov 24, 2023, at 23:38, PB2 ***@***.***> wrote:﻿
@jimwhitelaw
Would you be cool with submitting a PR?

**Comment by PowerBroker2** [comment]
Merged
