### ISSUE TITLE
Use own pid

### ISSUE THREAD

**Issue by Faceonlook** [PowerBroker2/ELMduino#199]
Hello i try to use my own pid please somebody can help me.

Pid:22028C
Header:7E0
for my e-golf

**Comment by Faceonlook** [comment]
Does this look good?

`if (myELM327.queryPID("22028C")) {
       response = myELM327.findResponse();  
       Serial.print("Response: "); Serial.println(response);
`

**Comment by PowerBroker2** [comment]
That might work if that's the only PID you're querying. Also note there seems to be a bug in `queryPID()` that is being actively worked (#198)

**Comment by Faceonlook** [comment]
Okay, I'll test this, thanks. Can you also please tell me how to set the header correctly?

**Comment by PowerBroker2** [comment]
I'm not familiar with setting headers. You might want to check the datasheet in the reference folder in this library.

Also, see this: https://github.com/PowerBroker2/ELMduino/issues/198#issuecomment-1853198890
