### ISSUE TITLE
Make PAYLOAD_LEN redefinable.

### ISSUE THREAD

**Issue by IW3IJQ** [PowerBroker2/ELMduino#22]
Now PAYLOAD_LEN is fixed to 40.
Some ECU have custom pids with custom reply.
For example mine reply with 36, 44 and 126 characters on ELM side.

**Comment by PowerBroker2** [comment]
Added this functionality in [the current **dev branch**](https://github.com/PowerBroker2/ELMduino/tree/dev). Can you test to see if it works for you?

Once the dev branch is validated, I'll merge it to master and re-release.

**Comment by IW3IJQ** [comment]
Thanks!
I have updated my code. 
Now I can't test it, but I will give you feedback as soon as possible.

ELM expect 7 bytes max queries and replies. To leave this limit  it need "AT AL" setting.
I send this after initialization. 
You could think of sending it automatically according to payload size.

**Comment by PowerBroker2** [comment]
That's a good point, I might add `AT AL` in `begin()` automatically. I'm guessing, however, this change won't affect normal PID queries (i.e. speed or rpm)?

**Comment by IW3IJQ** [comment]
ELM327 datasheet indicate only that this command remove the 7 bytes limit. So I think that's ok for normal PID queries.

**Comment by PowerBroker2** [comment]
Added `AT AL` in the dev branch

**Comment by PowerBroker2** [comment]
Fixed in [release 2.1.3](https://github.com/PowerBroker2/ELMduino/releases/tag/2.1.3). Thanks!
