### ISSUE TITLE
Sending false Command?

### ISSUE THREAD

**Issue by Faceonlook** [PowerBroker2/ELMduino#224]
`  
soc = myELM327.processPID(0x22, 0x028C, 1, 1);

if (myELM327.nb_rx_state == ELM_SUCCESS)
      {
       Serial.print("AKKU (%): ");
       Serial.println(soc);

      }
      else if (myELM327.nb_rx_state != ELM_GETTING_MSG)
      {
        myELM327.printError();
        Serial.print("FEHLER");
        tft.setTextColor(TFT_RED); // Textfarbe setzen
        tft.setTextSize(2); // Textgröße setzen
        tft.setCursor(0, 0); // Cursor setzen      
        tft.drawString("Fehler",  30, 60, 4);

      }

  delay(200); // Delay between reads
`

**Output**
Sending the following command/query: 22028C1
Service: 34
PID: 652
Long query detected
Query string: 22028C1

Why is the sending command 22028C1 it should be 22028C
The response should be: 62028C75

**Comment by jimwhitelaw** [comment]
The 1 at the end of the query string is added to tell the ELM device how many responses to expect. That is not an error and should not cause a problem. Can you post the serial/debug output you're receiving?

**Comment by Faceonlook** [comment]
**I have change this**
`soc = myELM327.processPID(0x22, 0x028C, 1, 4, 1.0, 0.0);`
**now i have the right output but how can i display the responseByte_0?**

All chars received: 62028C75
Expected response header: 62028C
Single response detected
64-bit response: 
	responseByte_0: 117
	responseByte_1: 0
	responseByte_2: 0
	responseByte_3: 0
	responseByte_4: 0
	responseByte_5: 0
	responseByte_6: 0
	responseByte_7: 0
WARNING: Number of payload chars is less than the number of expected response chars returned by ELM327 - returning 0
State of Charge: 0.00
0.00

**Comment by Faceonlook** [comment]
`   
uint8_t responseByte_0 = myELM327.responseByte_0;
Serial.println(responseByte_0, HEX); 
`
Is this correct?
