### ISSUE TITLE
ESP32 s3 BLE compatibility?

### ISSUE THREAD

**Issue by weeblebiker** [PowerBroker2/ELMduino#246]
Classic bluetooth isn't supported with the newer ESP32 S3s. they don't have the hardware.

Is Elmduino compatible with ESP32 BLE libraries?
BLEDevice.h
BLEUtils.h
BLEScan.h
BLEAdvertisedDevice.h

or does it work only with older ESP32s and BluetoothSerial.h

I have a ELM327 BLE dongle and ESP32 S3 based lilygo T-display S3 I'd like to work together 

I didn't find any BLE examples

 I'm presently using a macchina A0 OBD2 to ESP32 dongle with ESP NOW wireless to the T-display S3, but would rather use ELMDuino and a more prevalent BLE ELM327 dongle for future development since the macchina A0 dongle is often out of stock and expensive. The A0 also has some hardware issues that keep it from functioning well.

Thanks for developing this.

**Comment by PowerBroker2** [comment]
Sorry, but BLE is not supported. You could opt for a WiFi OBD2 scanner and take advantage of the ESP's WiFi interface instead.

**Comment by jimwhitelaw** [comment]
@weeblebiker, user @DerKleinePunk has [created an app](https://github.com/DerKleinePunk/ODB-ESP32-Reader/tree/main) using ELMduino with BLE. I haven't tried it myself, but perhaps there is something there may be of some use for you.

**Comment by DerKleinePunk** [comment]
No the BLE ist also not Working Currently
