### ISSUE TITLE
How can I use ELMduino over Uart?

### ISSUE THREAD

**Issue by beebrain** [PowerBroker2/ELMduino#31]
I have ELM32 but the Bluetooth module on ELM is broken.
I extracted the RX and TX line and connected them to my laptop. It's work.
I would like to know. How to connect them over arduino with your library?

**Comment by PowerBroker2** [comment]
Using hardware or software serial, connect RX to TX both ways between the Arduino and ELM327. Then use the appropriate library example.

**Comment by nices0325** [comment]
would you let me know the example link??? I have same situation with 'beebrain' plz...

**Comment by beebrain** [comment]
> would you let me know the example link??? I have same situation with 'beebrain' plz...

For my situation, I have changed the baud rate to 34800. Try to change the baud rate.
