### ISSUE TITLE
Hi,can you tell me BluetoothSerial.h source，thank you

### ISSUE THREAD

**Issue by zhangxueh** [PowerBroker2/ELMduino#32]
Hi, Thank you for your code, but I have a problem. I look at your code in "examples/ESP32_Bluetooth_Serial/ESP32_Bluetooth_Serial.ino", it have a  "BluetoothSerial.h" ,I can't find the source on the Internet. Can you tell me its link and it's library? or can you provide the code? Thank you.

**Comment by PowerBroker2** [comment]
If you're compiling for an ESP32, you already have the library as part of the NodeMCU core. If you're not compiling for an ESP32, the library will not work. [This, however, is the link to the BluetoothSerial.h file on GitHub](https://github.com/espressif/arduino-esp32/blob/master/libraries/BluetoothSerial/src/BluetoothSerial.h)

**Comment by zhangxueh** [comment]
OK, thank you
