### ISSUE TITLE
ERROR: ELM_NO_DATA on ESP32Dev device

### ISSUE THREAD

**Issue by i82hisaj** [PowerBroker2/ELMduino#40]
**Describe the bug**
Hello! First of all, many thanks for your library, what an excellent work! Nevertheless, I'm having some troubles while trying to use it with a ESP32Dev device. I'm continuously being shown the following error:

> Attempting to connect to ELM327...
> Connected to ELM327
> Payload received for rpm: NODATA
> 	ERROR: ELM_NO_DATA
> Payload received for kph: NODATA
> 	ERROR: ELM_NO_DATA

I have tested the ESP32_test.ino example, with a successful connection to the device, as follows:

> Attempting to connect to ELM327...
> Connected to ELM327
> Ensure your serial monitor line ending is set to 'Carriage Return'
> Type and send commands/queries to your ELM327 through the serial monitor
> >AT Z
> ELM327 v2.1
> >AT E0
> OK
> >AT S0
> OK
> >AT SP0
> OK
> >010C
> SEARCHING...
> 410C0B94
> 

I'm wondering if you could give me a clue about what's going on. Thanks in advance!

**To Reproduce**
Upload to a ESP32 device the code below.
Connect to ELM327 device

**Expected behavior**
Show values to .kph(), .rpm() and standard PIDs 

**Equipment**
Microcontroller: ESP32-Bit (programmable as ESP32 Dev Module), like this one: https://www.amazon.es/ESP32-Bit-Desarrollo-Bluetooth-Ethernet-ESP32-T/dp/B07GD4SGYM
OBD II Controller: OBD II Mini ELM327, like this one: https://www.amazon.es/Interfaz-Bluetooth-herramienta-an%C3%A1lisis-diagn%C3%B3stico/dp/B00WU97RH8
Car Model: Peugeot 206

**Code**
```C++
// modified test + my custom PIDs
// based purely on library

#include "BluetoothSerial.h"
#include "ELMduino.h"


#define ELM_PORT SerialBT
#define ESP_BLUETOOTH_NAME "ESP32"


BluetoothSerial SerialBT;
ELM327 myELM327;


void setup()
{
  //pinMode(LED_BUILTIN, OUTPUT);
  //digitalWrite(LED_BUILTIN, HIGH);

  Serial.begin(115200);
  //ELM_PORT.setPin("1234");
  ELM_PORT.begin(ESP_BLUETOOTH_NAME, true);

  Serial.println("Attempting to connect to ELM327...");

  if (!ELM_PORT.connect("OBDII"))
  //if (!ELM_PORT.connect("00:1d:a5:68:98:8d"))
  {
    Serial.println("Couldn't connect to OBD scanner - Phase 1");
    while (1);
  }

  if (!myELM327.begin(ELM_PORT))
  {
    Serial.println("Couldn't connect to OBD scanner - Phase 2");
    while (1);
  }
  
  Serial.println("Connected to ELM327");
  
/*  for (int a = 0; a < 10; ++a)
  {
    digitalWrite(LED_BUILTIN,HIGH); delay(100);
    digitalWrite(LED_BUILTIN,LOW); delay(100); 
  }
*/
}


void loop()
{
  int32_t rpm = -1;                     // Directo
  int32_t engineLoad = -1;              // A/2.55
  int32_t engineCoolant = -1;           // A - 40
  int32_t shortTermFuelTrimBank1 = -1;  // A/1.28 - 100
  int32_t longTermFuelTrimBank1 = -1;   // A/1.28 - 100
  int32_t intakeManifoldPressure = -1;  // A
  int32_t kph = -1;                     // Directo
  int32_t timingAdvance = -1;           // A/2 - 64
  int32_t intakeAir = -1;               // A - 40
  int32_t throttlePosition = -1;        // A/2.55
  

  /////////////////////////////////////////////////////// RPM
  float tempRPM = myELM327.rpm();
  
  Serial.print("Payload received for rpm: ");
  for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
    Serial.write(myELM327.payload[i]);
  Serial.println();
  
  if (myELM327.status == ELM_SUCCESS)
  {
    rpm = (int32_t)tempRPM;
    Serial.print("RPM: "); Serial.println(rpm);
  }
  else
      printError();

  /////////////////////////////////////////////////////// Kph
  float kphTemp = myELM327.kph();
  
  Serial.print("Payload received for kph: ");
  for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
    Serial.write(myELM327.payload[i]);
  Serial.println();
  
  if (myELM327.status == ELM_SUCCESS)
  {
    kph = (int32_t)kphTemp;
    Serial.print("KPH: "); Serial.println(kph);
  }
  else
      printError();

  /////////////////////////////////////////////////////// Engine Load
  if (myELM327.queryPID(SERVICE_01, ENGINE_LOAD))
  {
    int32_t engineLoadTemp = myELM327.findResponse();

    Serial.print("Payload received for Engine Load: ");
    for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
      Serial.write(myELM327.payload[i]);
    Serial.println();
    
    if (myELM327.status == ELM_SUCCESS)
    {
      engineLoad = engineLoadTemp/2.55;
      Serial.print("EngineLoad: "); Serial.println(engineLoad);
    }
    else
      printError();
  }


  /////////////////////////////////////////////////////// engineCoolant = -1;       // A - 40
  if (myELM327.queryPID(SERVICE_01, ENGINE_COOLANT_TEMP))
  {
    int32_t engineCoolantTemp = myELM327.findResponse();

    Serial.print("Payload received for Engine Coolant: ");
    for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
      Serial.write(myELM327.payload[i]);
    Serial.println();
    
    if (myELM327.status == ELM_SUCCESS)
    {
      engineCoolant = engineCoolantTemp - 40;
      Serial.print("EngineCoolant: "); Serial.println(engineCoolant);
    }
    else
      printError();
  }


  /////////////////////////////////////////////////////// shortTermFuelTrimBank1 = -1;  // A/1.28 - 100
  if (myELM327.queryPID(SERVICE_01, SHORT_TERM_FUEL_TRIM_BANK_1))
  {
    int32_t shortTermFuelTrimBank1Temp = myELM327.findResponse();

    Serial.print("Payload received for Short Term Fuel Trim Bank 1: ");
    for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
      Serial.write(myELM327.payload[i]);
    Serial.println();
    
    if (myELM327.status == ELM_SUCCESS)
    {
      shortTermFuelTrimBank1 = shortTermFuelTrimBank1Temp/1.28 - 100;
      Serial.print("Short Term Fuel Trim Bank1: "); Serial.println(shortTermFuelTrimBank1);
    }
    else
      printError();
  }

  /////////////////////////////////////////////////////// longTermFuelTrimBank1 = -1;   // A/1.28 - 100
  if (myELM327.queryPID(SERVICE_01, LONG_TERM_FUEL_TRIM_BANK_1))
  {
    int32_t longTermFuelTrimBank1Temp = myELM327.findResponse();

    Serial.print("Payload received for Long Term Fuel Trim Bank 1: ");
    for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
      Serial.write(myELM327.payload[i]);
    Serial.println();
    
    if (myELM327.status == ELM_SUCCESS)
    {
      longTermFuelTrimBank1 = longTermFuelTrimBank1Temp/1.28 - 100;
      Serial.print("Long Term Fuel Trim Bank1: "); Serial.println(longTermFuelTrimBank1);
    }
    else
      printError();
  }

  /////////////////////////////////////////////////////// intakeManifoldPressure = -1;  // A
  if (myELM327.queryPID(SERVICE_01, INTAKE_MANIFOLD_ABS_PRESSURE))
  {
    int32_t intakeManifoldPressureTemp = myELM327.findResponse();

    Serial.print("Payload received for Intake Manifold Absolute Pressure: ");
    for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
      Serial.write(myELM327.payload[i]);
    Serial.println();
    
    if (myELM327.status == ELM_SUCCESS)
    {
      intakeManifoldPressure = intakeManifoldPressureTemp;
      Serial.print("Intake Manifold Absolute Pressure: "); Serial.println(intakeManifoldPressure);
    }
    else
      printError();
  }


  /////////////////////////////////////////////////////// timingAdvance = -1;           // A/2 - 64
  if (myELM327.queryPID(SERVICE_01, TIMING_ADVANCE))
  {
    int32_t timingAdvanceTemp = myELM327.findResponse();

    Serial.print("Payload received for Timing Advance: ");
    for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
      Serial.write(myELM327.payload[i]);
    Serial.println();
    
    if (myELM327.status == ELM_SUCCESS)
    {
      timingAdvance = timingAdvanceTemp;
      Serial.print("Timing Advance: "); Serial.println(timingAdvance);
    }
    else
      printError();
  }

  /////////////////////////////////////////////////////// intakeAir = -1;               // A - 40
  if (myELM327.queryPID(SERVICE_01, INTAKE_AIR_TEMP))
  {
    int32_t intakeAirTemp = myELM327.findResponse();

    Serial.print("Payload received for Intake Air Temp: ");
    for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
      Serial.write(myELM327.payload[i]);
    Serial.println();
    
    if (myELM327.status == ELM_SUCCESS)
    {
      intakeAir = intakeAirTemp - 40;
      Serial.print("Intake Air Temp: "); Serial.println(intakeAir);
    }
    else
      printError();
  }

  /////////////////////////////////////////////////////// throttlePosition = -1;        // A/2.55
  if (myELM327.queryPID(SERVICE_01, THROTTLE_POSITION))
  {
    int32_t throttlePositionTemp = myELM327.findResponse();

    Serial.print("Payload received for Throttle Position: ");
    for (byte i = 0; i < myELM327.PAYLOAD_LEN; i++)
      Serial.write(myELM327.payload[i]);
    Serial.println();
    
    if (myELM327.status == ELM_SUCCESS)
    {
      throttlePosition = throttlePositionTemp/2.55;
      Serial.print("Throttle Position: "); Serial.println(throttlePosition);
    }
    else
      printError();
  }



/*  for (int a = 0; a < 5; ++a)
  {
    digitalWrite(LED_BUILTIN,HIGH);
    delay(200);
    digitalWrite(LED_BUILTIN,LOW);
    delay(200); 
  }
  */
}


void printError()
{
  if (myELM327.status == ELM_SUCCESS)
    Serial.println(F("\tELM_SUCCESS"));
  else if (myELM327.status == ELM_NO_RESPONSE)
    Serial.println(F("\tERROR: ELM_NO_RESPONSE"));
  else if (myELM327.status == ELM_BUFFER_OVERFLOW)
    Serial.println(F("\tERROR: ELM_BUFFER_OVERFLOW"));
  else if (myELM327.status == ELM_GARBAGE)
    Serial.println(F("\tERROR: ELM_GARBAGE"));
  else if (myELM327.status == ELM_UNABLE_TO_CONNECT)
    Serial.println(F("\tERROR: ELM_UNABLE_TO_CONNECT"));
  else if (myELM327.status == ELM_NO_DATA)
    Serial.println(F("\tERROR: ELM_NO_DATA"));
  else if (myELM327.status == ELM_STOPPED)
    Serial.println(F("\tERROR: ELM_STOPPED"));
  else if (myELM327.status == ELM_TIMEOUT)
    Serial.println(F("\tERROR: ELM_TIMEOUT"));
  else if (myELM327.status == ELM_GENERAL_ERROR)
    Serial.println(F("\tERROR: ELM_GENERAL_ERROR"));

  delay(500);
}
```

**Wiring**
N/A

**Screenshots**
N/A

**Additional Context**
N/A

**Troubleshooting Connection Issues**
- Try 38400 baud instead of 115200 ---> Tried with no success.
- If using an HC-05 for communication, [ensure it's configured properly](https://forum.arduino.cc/index.php?topic=600014.msg4159554#msg4159554) ---> N/A
- Ensure the car is on and running during troubleshooting ---> Car running
-Also tested with BT mac address, and providing PIN code, with no success.

**Comment by PowerBroker2** [comment]
I see that the ELM327 is responding to your queries with `NO DATA`. This means that for some reason the ELM327 can't get the data off the diagnostics computer and is more of a car <-> ELM issue instead of an ELM <-> Arduino issue.

What could be going wrong:
- Car isn't in the correct state (i.e. on and running), but you've already said this is the case
- The Service ID/PID are incorrect, but you seem to be using the correct ones
- Generic bug with the ELM327 or diagnostics computer, but this is very unlikely
- The ELM327 isn't correctly configured by the lib - Try the following with the test sketch again and post the results:
```
AT Z
AT E0
AT S0
AT AL
AT TP A0
010C
010D
```

**Comment by patfelst** [comment]
You received a response for RPM of 410C0B94 = 741 RPM using the test example. My guess is it's timing out when you query RPM in your loop code. Try increasing the timeout value from 1000 to 5000 for example.

Also you you have a few type problems to fix, e.g. `engineLoad = engineLoadTemp/2.55;` where `engineLoad` is an integer (int32_t), you should probably make it a float.

**Comment by PowerBroker2** [comment]
> You received a response for RPM of 410C0B94 = 741 RPM using the test example. My guess is it's timing out when you query RPM in your loop code. Try increasing the timeout value from 1000 to 5000 for example.

It's not timing out because a message was received from the ELM, but was the string `NO DATA`

**Comment by patfelst** [comment]
ah of course, apologies. Odd that he did receive a response with the test program though.

**Comment by i82hisaj** [comment]
> You received a response for RPM of 410C0B94 = 741 RPM using the test example. My guess is it's timing out when you query RPM in your loop code. Try increasing the timeout value from 1000 to 5000 for example.
> 
> Also you you have a few type problems to fix, e.g. `engineLoad = engineLoadTemp/2.55;` where `engineLoad` is an integer (int32_t), you should probably make it a float.

Good catch about the float/integer mismatch. I will fix it! 👍

**Comment by i82hisaj** [comment]
> I see that the ELM327 is responding to your queries with `NO DATA`. This means that for some reason the ELM327 can't get the data off the diagnostics computer and is more of a car <-> ELM issue instead of an ELM <-> Arduino issue.
> 
> What could be going wrong:
> 
> * Car isn't in the correct state (i.e. on and running), but you've already said this is the case
> * The Service ID/PID are incorrect, but you seem to be using the correct ones
> * Generic bug with the ELM327 or diagnostics computer, but this is very unlikely
> * The ELM327 isn't correctly configured by the lib - Try the following with the test sketch again and post the results:
> 
> ```
> AT Z
> AT E0
> AT S0
> AT AL
> AT TP A0
> 010C
> 010D
> ```

Ok, I will test what you are requesting. I will post the results as soon as possible (in a few hours). Thanks!

**Comment by i82hisaj** [comment]
Hi, I could test it earlier than expected. Here are the results of the test:

> AT Z
> ELM327 v2.1
> >AT E0
> OK
> >AT S0
> OK
> >AT AL
> OK
> >AT TP A0
> OK
> >010C
> NO DATA
> >010D
> NO DATA
> >

**Comment by PowerBroker2** [comment]
Seems like your ELM327 doesn't like something about the settings the lib uses, you can edit your local copy of the library to adjust what configuration settings works for you

**Comment by i82hisaj** [comment]
Hello again,

Many thanks for your help. I have investigated a bit, and I have obtained additional information from the ELM327 using Torque for it (BTW, it works perfectly fine in Torque). I have noticed that my ELM327 uses ISO14230-4 KWP 5bd protocol. I have changed the declaration of the class in file "ELMduino.h" to the following:

```
	bool begin(Stream& stream, char protocol='4', uint16_t payloadLen = 40);
	bool initializeELM(char protocol='4');
```

...as the headers in the file established that this protocol was identified as '4':

```
const char ISO_14230_5_BAUD_INIT      = '4';
const char ISO_14230_FAST_INIT        = '5';
```

After that, I have restarted Arduino IDE and compiled and uploaded again my code to the ESP32. Unfortunately, I had the same results:

> ets Jun  8 2016 00:22:57
> 
> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:1
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1216
> ho 0 tail 12 room 4
> load:0x40078000,len:9720
> ho 0 tail 12 room 4
> load:0x40080400,len:6352
> entry 0x400806b8
> Attempting to connect to ELM327...
> Connected to ELM327
> Payload received for rpm: NODATA
> Payload received for kph: NODATA
> Payload received for Engine Load: NODATA


After that, I have also tested with protocol '5', with the same results again.

Is there any other place in the library where I can make adjustments? Thanks in advance!

**Comment by i82hisaj** [comment]
Hello again,

Something else I have tested (again without success). I have also modified ELMduino.cpp to this:

```
bool ELM327::initializeELM(char protocol)
{
	char command[10] = { '\0' };
	connected = false;
	
	sendCommand(RESET_ALL);
        delay(500);

	sendCommand(ECHO_OFF);
	delay(500);

	sendCommand(PRINTING_SPACES_OFF);
	delay(500);
	
	//sendCommand(ALLOW_LONG_MESSAGES);
	//delay(100);

```
...as the test example didn't use long messages. But as said, no success with this (both with protocol 4 and 0).

**Comment by PowerBroker2** [comment]
In that case, use what worked initially:

```
AT Z
AT E0
AT S0
AT SP0
```

**Comment by PowerBroker2** [comment]
Closing for now, but if you still have issues, feel free to reopen

**Comment by i82hisaj** [comment]
Many thanks for your help with this. I'm on my holidays these days, so I have no chance to continue making tests. ;)
In any case, as it seems to be an issue with my device, no worries about closing the ticket. If I make any progress with the code, I will let you know.
Best regards!

**Comment by nices0325** [comment]
I have a same issue withe my elmduino project. I have successfully connected and gotten the data but it suddenly doesn't work... what would be the problem. If you configure what was the problem and solved it plz let me know

**Comment by nomidaepapi** [comment]
Hi @PowerBroker2 , I would like to request to open this ticket one more time. 

My set up is a ELM327 Bluetooth adapter and esp32 audrino.

I have two cars a Lexus GS 300, 2001 and a Toyota sienna 2014.

when I try the test example to try reading the RPM. It is unsuccessful on the Lexus GS 300 and see is NO DATA; but for the Toyota sienna 2014, it reads completely fine and displays the RPM (the Bluetooth connection is successful in both cars). I have read through many threads and try to fix this for three weeks but I’m running out of ideas.

This thread was very useful as a problem is similar to mine. I’m very strong with programming, but I do not understand what I have to do or fix in your opensource code to make it work with my Lexus. Is there any way you can help?

**Comment by VinicioAM** [comment]
Hello. I'm facing the same problem. 

When I run the example 'ESP32_Bluetooth_Serial', which makes a lot of data request, I just get 'NO DATA' answer.
When I run the example 'ESP32_test', then send:

AT Z
AT E0
AT S0
AT AL
AT TP A0
010C
010D

I can receive the data (encoded), and it is correct.

Is there any way to fix it by using the example 'ESP32_Bluetooth_Serial'?
I don't have enough experience in C++ to fix it by myself.

thank so much for any help.

**Comment by PowerBroker2** [comment]
If you have a different startup procedure that works while the default one doesn't, you might try making an `initializeELM()` function at the sketch level with the proper configuration commands. Should be a pretty easy copy, paste, and edit. Here is the original function for reference:

https://github.com/PowerBroker2/ELMduino/blob/636aa957f6f7d6ff01bf41fbfce004c1efc5883c/src/ELMduino.cpp#L85-L145

**Comment by VinicioAM** [comment]
Yes, Mr. P_B, I did it already.

Here is one of the my attempts:

`	delay(10000);
	sendCommand_Blocking(RESET_ALL);
	delay(1000);

	sendCommand_Blocking(ECHO_OFF);
	delay(1000);

	sendCommand_Blocking(PRINTING_SPACES_OFF);
	delay(1000);

	sendCommand_Blocking(ALLOW_LONG_MESSAGES);
	delay(1000);

	sendCommand_Blocking("AT TP A0");
	delay(1000);

	sendCommand_Blocking(DISP_CURRENT_PROTOCOL);
	delay(10000);

	sendCommand_Blocking("AT SP 7");
	delay(10000);

	sendCommand_Blocking(DISP_CURRENT_PROTOCOL);
	delay(10000);`

This is exactly the same config that I do when I use 'ESP32_test', send 010C and get the encoded RPM.
I get the configuration sucessfull. Anyway, when using 'ESP32_Bluetooth_Serial', it still being delivered 'NODATA' (even with the new config). 

There is a point: to see RPM, I send 010C. Anyway, in the debug mode inside 'ESP32_Bluetooth_Serial' the message sent to ELM  by using rpm function is not exactly 010C (It is 0112). Does this hexadecimal to decimal conversion have any problem?

Second point: might it be a timeout/too fast/wrong baud rate problem? 

I have already tried change 
`	// Set data timeout
	sprintf(command, SET_TIMEOUT_TO_H_X_4MS, dataTimeout / 4);
	sendCommand_Blocking(command);
	delay(100);`
to 1000ms, 2000ms, 5000ms, 100ms, 10000ms, 50ms, 0ms... does not work.

Tried all baud rates too.. Does not work.

Any suggestion?

**Comment by DerKleinePunk** [comment]
I don't know it ist possible you have the same probleme as me.

The AT Commands not Understand from my ELM it looks as an Timing Problem on ESP32.
When i use an Android Terminal it work but not work  in ESP Software.
You Receive an OK on the AT Commands ? When not you can try my Fork

https://github.com/DerKleinePunk/ELMduino
https://github.com/DerKleinePunk/ODB-ESP32-Reader My Littel Test Projekt
