### ISSUE TITLE
rpm() function 

### ISSUE THREAD

**Issue by adamkovari** [PowerBroker2/ELMduino#48]
Hi, if I call the rpm() function, I should get 2 bytes as answer, but I get these 2 bytes two times, so for example: 0D8C would be the right answer, but I get 0D8C0D8C, if I give the explicit AT cmd 010C to the ELM327, get 4 bytes as an answer, as well. Do you know why is this happenning?
Thank you!
@PowerBroker2

**Comment by PowerBroker2** [comment]
That's just how the ELM327 works for some reason. The library handles double responses, so it shouldn't be an issue
