### ISSUE TITLE
Response byte ordering.

### ISSUE THREAD

**Issue by stumunro74** [PowerBroker2/ELMduino#57]
Have been using the latest version 2.4.1 which now has the monitorStatus method.

Reading the https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_01_PID_01

This refers to byte 1, bit 7 being the MIL status bit.

> A request for this PID returns 4 bytes of data (Big-endian).

>When using Bit-Encoded-Notation, quantities like C4 means bit 4 from data byte C. Each bit is numerated from 0 to 7, so 7 is the most significant bit and 0 is the least significant bit (See below).

> The first byte(A) contains two pieces of information. Bit A7 (MSB of byte A, the first byte) indicates whether or not the MIL (check engine light) is illuminated. 

I tried to read this out of response_byte0, but the data didn't look right. Worked out that its actually in response_byte3 as this is the 4th byte from the right in binary terms.

My question is.

1. Is Wikipedia wrong labeling this as byte A and referring to it as the first byte and its should be should it be byte D last byte? 
2. Should the response bytes be stored in the same order??
3. Are both correct but it just needs to be made clear that response bytes in the library are reversed and in little endian?

**Comment by PowerBroker2** [comment]
For this PID, you should bit masking the returned value of `monitorStatus()`. That should give you the correct answer, if not, then there's a bug somewhere
