### ISSUE TITLE
DISP_ID is incorrect

### ISSUE THREAD

**Issue by lhn1324** [PowerBroker2/ELMduino#6]
const char * const DISP_ID                    = "AT HI";     // General

ELM327 datasheet page 17

I 
[ Identify yourself ]
Issuing this command causes the chip to identify
itself, by printing the startup product ID string (currently
‘ELM327 v2.0’). Software can use this to determine
exactly which integrated circuit it is talking to, without
having to reset the IC.

**Comment by PowerBroker2** [comment]
Fixed in 1.1.8
