### ISSUE TITLE
support on stm32

### ISSUE THREAD

**Issue by nices0325** [PowerBroker2/ELMduino#61]
I'm on my project developing car connected internet of things using lte catm1 module. Do you have any plan to modify the code that it works on arm mbed IDE to run on stm board?? I have willing to pay you a little for this project.. thank you

**Comment by PowerBroker2** [comment]
I believe it is already compatible with STM arduinos - are you getting compile-time errors?

**Comment by nices0325** [comment]
actually i mean, working on the arm mbed IDE .. sorry for confusing

**Comment by PowerBroker2** [comment]
Never used that IDE before. If it allows the use of custom libs like this one, you shouldn't have any issues using it.
