### ISSUE TITLE
Possible integer overflow?

### ISSUE THREAD

**Issue by brainfoolong** [PowerBroker2/ELMduino#62]
Hi!

I am currently having rare weird issues in my program. For me, some numbers in other variables in a struct changes with no obvious reasons. I am reading `kph` and store that return value into a struct property.

As i am no c++ expert, i want to kindly ask the question, if this can overflow in some cases.

It is fact that kph sometimes gives extraordinary high numbers when something weird is happening on the OBD device.

So, lets face the code: - I use this function

https://github.com/PowerBroker2/ELMduino/blob/4e691cf09e1bb9743bddf5b53ad51146637a0fe6/src/ELMduino.cpp#L787

I noticed that it casts to `int32_t`. This function internally calls `findResponse` which returns a `uint64_t`.
https://github.com/PowerBroker2/ELMduino/blob/4e691cf09e1bb9743bddf5b53ad51146637a0fe6/src/ELMduino.cpp#L2489

So it ends up in a `uint64_t` to `int32_t ` cast - Is it technically possible that this does overflow and effect other memory in code?

**Comment by PowerBroker2** [comment]
The 64-bit return value is for long responses from custom PID queries. If the library implicitly typecasts the return value of `findResponse()`, it means not all of the 64 bits have data. For instance, the function 'kph()' will never need more than 32-bits unless you plan on driving faster than 4,294,967,295 kph 😂. As for the memory integrity issue, the typecasting will not harm your Arduino's memory nor will it accidentally change any other variable's values. In short, this isn't really something you need to worry about unless you're getting inaccurate values from the lib (I could still have a bug in it)

**Comment by brainfoolong** [comment]
Thank you.
