### ISSUE TITLE
PID Fuel System Status

### ISSUE THREAD

**Issue by technic98** [PowerBroker2/ELMduino#67]
Hello,
I need a example to read the fuel system status. 
I tried:
```C++
if (myELM327.queryPID(SERVICE_01, FUEL_SYSTEM_STATUS))
 {
      if (myELM327.status == ELM_SUCCESS)
      {
           int fuelSystem = myELM327.findResponse();
       }
}
```
But there is no valid response.
Can someone give me a short example.

**Comment by PowerBroker2** [comment]
```C++
  uint16_t status;
  uint16_t tempStatus = myELM327.fuelSystemStatus();

  if (myELM327.status == ELM_SUCCESS)
  {
    status = tempStatus;
    Serial.print("RPM: "); Serial.println(status);
  }
  else
    myELM327.printError();
```

**Comment by technic98** [comment]
Thank you. 
Is the return Fuel System Status #1 or #1 and #2 together?
[https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_01_PID_03](url)

**Comment by PowerBroker2** [comment]
I don't understand the question, but the function returns the values consistent with  [this encoding](https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_01_PID_03)

**Comment by technic98** [comment]
The request for this PID returns 2 bytes of data. 
First Byte for Fuel System Status #1 and the second Byte for Fuel System Status #2.
How can I get the first Byte Data to read Fuel System Status #1?

**Comment by PowerBroker2** [comment]
The code snippet returns a 16-bit number (2 bytes) that includes both bytes you're looking for. The order of bits/bytes is consistent with [https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_01_PID_03](https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_01_PID_03)
