### ISSUE TITLE
Electric vehicle support

### ISSUE THREAD

**Issue by LucaBertuolo** [PowerBroker2/ELMduino#77]
Hello,
does ELMduino support electric vehicle?
It will be usefull to get even only battery percentage (some brands like Opel/Peugeot does not show battery percentage)

**Comment by cyberelectronics** [comment]
Using ELMduino on [Hyundai Kona EV](https://youtu.be/WdHU3YUXCjA)

**Comment by LucaBertuolo** [comment]
@cyberelectronics 
Really nice project!

Mine will be easier, I was thinking to use a TTGO T5 V2.3 to connect the ESP32 to the ELM327 and show the battery percentage on the e-ink display.
Low power, and just some essential info.

Feel free to do the same, you have too much great skill than me :)
