### ISSUE TITLE
Know if lights are on 

### ISSUE THREAD

**Issue by rodrigoaraujo02** [PowerBroker2/ELMduino#79]
Hi!

I've used your library to get rpm and temperature info from my BMW E46! So far I've discovered It heats more then it should :/ So, thanks for publishing this library!

Thing is, have some LED's according to the RPM, but I wanted them to be stronger during the day and lighter during the night. My radio gets that information and I believe it's throug CANBUS as well, so could you help me find if that information is available? Or how can I get it?

Thanks!

**Comment by PowerBroker2** [comment]
Glad you've found use for the library!

It might be possible to poll for LED status, but you'd need to know the exact PID (if it exists at all) - which is likely _not_ standard and is specific to your car's make/model (and perhaps year). In this case, google will be much more helpful than I can be. A good starting place might be here: [https://f30.bimmerpost.com/forums/showthread.php?t=1483707](https://f30.bimmerpost.com/forums/showthread.php?t=1483707)
