### ISSUE TITLE
Supported Hardwares

### ISSUE THREAD

**Issue by sgtJohnny** [PowerBroker2/ELMduino#88]
The lib looks very nice and neatly written, but what i'm missing is hardware description that lists supported devices, for example which type or Arduino can be used.

I want to use the Adafruit Huzza32 (ESP-VROOM-32), do you know if this is supported?

Also it would be very nice to have a "tutorial" on how to get started with hardware.

**Comment by PowerBroker2** [comment]
Yup, that board should be compatible with the library. If you're using an ESP32 with built-in bluetooth (like the one you linked), it should be as simple as plugging the ELM327 into your car and running the example ESP32 sketch.
