### ISSUE TITLE
Debug cannot be switched off

### ISSUE THREAD

**Issue by sixtybi** [PowerBroker2/ELMduino#89]
I can't turn off serial debugging.
If I execute ELM_PORT.begin() with the second parameter disabled, I can't connect to OBD adapter.
If I set it to true, I can connect, everything works fine, but I get all the debug messages too.
Is there a way to disable debugging?
As a WA I have downgraded the package, but it would be great to have a solution with the latest version.
Thanks!

**Comment by PowerBroker2** [comment]
Please post all the contextual details about your project including (but not limited to) the code you're using. Any additional data on error codes or anything else helps, too

**Comment by sixtybi** [comment]
Here is my code:

#define SIM800L_IP5306_VERSION_20190610

/*
  OBD_Processor.ino  for SafeString V4.0.0+

  Example of using SafeString to process Car OnBoardData

  by Matthew Ford
  Copyright(c)2020 Forward Computing and Control Pty. Ltd.
  This example code is in the public domain.

  download and install the SafeString library V4.0.0+ from Arduino library manager
  or from www.forward.com.au/pfod/ArduinoProgramming/SafeString/index.html
*/

#include "ELMduino.h"

#include "SafeString.h"
// see https://github.com/PowerBroker2/ELMduino/issues/44#issuecomment-712617781
//Rawdata from OBD:
// some test data
char rawData[] = "7F22127F22127F22127F22127F221203E0:620101FFF7E71:FF8A00000000832:00240ED71713133:141713000010C14:22C12800008B005:00450B0000434B6:000019A80000187:1200200EE70D018:7B0000000003E8";

// where to store the results
struct dataFrames_struct {
  char frames[9][20]; // 9 frames each of 20chars
};

typedef struct dataFrames_struct dataFrames; // create a simple name for this type of data
dataFrames results; // this struct will hold the results

uint8_t address[6]  = {0x00, 0x04, 0x3E, 0x6F, 0x2B, 0x0C};

#include "BluetoothSerial.h"

BluetoothSerial SerialBT;

#define ELM_PORT   SerialBT

ELM327 myELM327;

void setup() {
  // Open serial communications and wait a few seconds
  Serial.begin(115200);
  for (int i = 10; i > 0; i--) {
    Serial.print(' '); Serial.print(i);
    delay(500);
  }
  Serial.println();
  SafeString::setOutput(Serial);
    ELM_PORT.setPin("0000");         // OBDLink LX
    //  ELM_PORT.setPin("1234");         // Tibi
    ELM_PORT.begin("boost", false);
    delay(1000);
    if (!ELM_PORT.connect(address))   // Device name of iCar Vgate pro BT4.0 OBD adapter
    {
      Serial.println("Couldn't connect to OBD scanner - Phase 1");
      ESP.restart();
    }
    if (!myELM327.begin(ELM_PORT, '6')) { // select protocol '6'
      //   if (!myELM327.begin(ELM_PORT,true,2000)){ // select protocol '6'
      Serial.println("Couldn't connect to OBD scanner - Phase 2");
      delay(1000);
      ESP.restart();
    }
    Serial.println("Connected to ELM327");
    myELM327.PAYLOAD_LEN = 150;
//    myELM327.sendCommand("ATD");
//    myELM327.sendCommand("ATZ");
//    myELM327.sendCommand("ATE0");
//    myELM327.sendCommand("ATL0");
//    myELM327.sendCommand("ATS0");
//    myELM327.sendCommand("ATH1");
//    myELM327.sendCommand("AT0");
//    myELM327.sendCommand("ATSTFF");
//    myELM327.sendCommand("ATFE");
//    myELM327.sendCommand("ATSP6");
//    myELM327.sendCommand("ATCRA7EC");

}

void clearResultFrames(dataFrames & results) {
  for (int i = 0; i < 9; i++) {
    results.frames[i][0] = '\0';
  }
}

// format is <headerBytes> then <frameNumberByte>:<frameDataBytes> repeated
void processPayload(char *OBDdata, dataFrames & results) {
  clearResultFrames(results);
  cSFP(data, OBDdata); // wrap in a SafeString, use strlen(OBDdata) to set the capacity since ELMduino terminates the returned data char[]
  //Serial.println(OBDdata);
  int idx = data.indexOf(':'); // skip over header and find first delimiter
  while (idx >= 0) {
    int frameIdx = data[idx - 1] - '0'; // the char before :
    if ((frameIdx < 0) || (frameIdx > 8)) { // error in frame number skip this frame, print a message here
      SafeString::Output.print("frameIdx:"); SafeString::Output.print(frameIdx); SafeString::Output.print(" outside range data: "); data.debug();
      idx = data.indexOf(':', idx + 1); // step over : and find next :
      continue;
    }
    cSFA(frame, results.frames[frameIdx]); // wrap a result frame in a SafeString to store this frame's data
    idx++; // step over :
    int nextIdx = data.indexOf(':', idx); // find next : -1 if not found
    if (nextIdx > 0) {
      data.substring(frame, idx, nextIdx - 1); // next : found so take chars upto 1 char before next :
    } else {
      data.substring(frame, idx, nextIdx); // next : not found so take all the remaining chars as this field
    }
    SafeString::Output.print("frameIdx:"); SafeString::Output.print(frameIdx); SafeString::Output.print(" "); frame.debug();
    idx = nextIdx; // step onto next frame
  }
}

int convertToInt(char* dataFrame, unsigned int offset, unsigned int numberBytes) {
  // define a local SafeString on the stack for this method
  cSFP(frame, dataFrame);
  cSF(hexSubString, frame.capacity()); // allow for taking entire frame as a substring
  frame.substring(hexSubString, offset, offset + (numberBytes * 2)); // endIdx in exclusive in SafeString V2+
  hexSubString.debug(F(" hex number "));
  long num = 0;
  if (!hexSubString.hexToLong(num)) {
    hexSubString.debug(F(" invalid hex number "));
  }
  SafeString::Output.print(F(" hexToLong:"));SafeString::Output.println(num);
  return num;
}

void printBatteryVolts(dataFrames & results) {
  float BATTv = convertToInt(results.frames[2], 4, 2) / 10.0;
  Serial.print("Battery Volts:"); Serial.println(BATTv, 1);
}

bool haveData = true;

void loop() {
  // .....
  // read in rawData via ODB
    myELM327.sendCommand("AT SH 7E4");       // Set Header BMS
    if (myELM327.queryPID("2101")) {      // BMS PID = hex 22 0101 => dec 34, 257
      char* payload = myELM327.payload;
      //size_t payloadLen = myELM327.recBytes; // But ELMduino terminates the result with '\0' so can just use strlen()
      processPayload(payload, results);
      printBatteryVolts(results); // plus other data
    }
    delay(30000);
  // test data code
/*  if (haveData) { // use test data instead of reading OBD
    char *payload = rawData;
    processPayload(payload, results);
    printBatteryVolts(results); // plus other data
    haveData = false; // only do this once
  }*/
}

This can't connect to my obdlink lx.
If I replace the line
    ELM_PORT.begin("boost", false);
to
    ELM_PORT.begin("boost", true);

It will connect, but I will get debug messages in the serial console.
For example:
Clearing input serial buffer
Sending the following command/query: AT D
	Received char: A
	Received char: T
	Received char:  
	Received char: D
	Received char: \r
	Received char: O
	Received char: K
	Received char: \r
	Received char: \r
	Received char: >
Delimiter found
All chars received: ATDOK
Clearing input serial buffer
Sending the following command/query: AT Z
	Received char: A
	Received char: T
	Received char:  
	Received char: Z
	Received char: \r
All chars received: ATZ
Timeout detected with overflow of 0ms
Clearing input serial buffer
Sending the following command/query: AT E0
	Received char: \r
	Received char: \r
	Received char: E
	Received char: L
	Received char: M
	Received char: 3
	Received char: 2
	Received char: 7
	Received char:  
	Received char: v
	Received char: 1
	Received char: .
	Received char: 4
	Received char: b
	Received char: \r
	Received char: \r
	Received char: >
Delimiter found
All chars received: ELM327v14b
Clearing input serial buffer
Sending the following command/query: AT S0
	Received char: A
	Received char: T
	Received char:  
	Received char: S
	Received char: 0
	Received char: \r
	Received char: O
	Received char: K
	Received char: \r
	Received char: \r
	Received char: >
Delimiter found
All chars received: ATS0OK
Clearing input serial buffer
Sending the following command/query: AT AL
	Received char: A
	Received char: T
	Received char:  
	Received char: A
	Received char: L
	Received char: \r
	Received char: O
	Received char: K
	Received char: \r
	Received char: \r
	Received char: >
Delimiter found
All chars received: ATALOK
Clearing input serial buffer
Sending the following command/query: AT ST 00
	Received char: A
	Received char: T
	Received char:  
	Received char: S
	Received char: T
	Received char:  
	Received char: 0
	Received char: 0
	Received char: \r
	Received char: O
	Received char: K
	Received char: \r
	Received char: \r
	Received char: >
Delimiter found
All chars received: ATST00OK
Clearing input serial buffer
Sending the following command/query: AT TP A0
	Received char: A
	Received char: T
	Received char:  
	Received char: T
	Received char: P
	Received char:  
	Received char: A
	Received char: 0
	Received char: \r
	Received char: O
	Received char: K
	Received char: \r
	Received char: \r
	Received char: >
Delimiter found
All chars received: ATTPA0OK
Connected to ELM327
Clearing input serial buffer
Sending the following command/query: AT SH 7E4
	Received char: A
	Received char: T
	Received char:  
	Received char: S
	Received char: H
	Received char:  
	Received char: 7
	Received char: E
	Received char: 4
	Received char: \r
	Received char: O
	Received char: K
	Received char: \r
	Received char: \r
	Received char: >
Delimiter found
All chars received: ATSH7E4OK


So I can't disable debugging in the newest version (2.6.1)

**Comment by sixtybi** [comment]
I have realized, after analyzing the source code, this should be changed not there, I mentioned earlier (it was suggested by someone in a discussion.)
So, to switched off debugging should be changed here:
myELM327.begin(ELM_PORT, true,2000,'6',200);
Second parameter should be set to false to disable debugging.
And the fifth parameter is maximum response length which caused a lot of trouble for me with my new obdlink lx adapter.

**Comment by sixtybi** [comment]
I am closing this issue as I have figured it out why it was wrong for me.
