### ISSUE TITLE
ways to increase refresh rate

### ISSUE THREAD

**Issue by aden16rus** [PowerBroker2/ELMduino#91]
hi it's great library but i faces with low information refresh rate. when i show rpm i expect actual value but it appears after 1-1.5s.

I uses arduino uno  with 3.5 display shield and hc-05 bluetooth module on 38400 serial speed

are there exists ways to increase data refresh speed?

i don't try to increase baud rate speed to 115200 yet, maybe it can help but i don't sure.

**Comment by PowerBroker2** [comment]
If you're using the latest version of the library AND you don't have any blocking code, the only ways I can see speeding up the refresh rate is to use a higher baud and/or use a more powerful microcontroller.
