### ISSUE TITLE
is it possible to pull time since engine start in milliseconds?

### ISSUE THREAD

**Issue by qqm55** [PowerBroker2/ELMduino#96]
currently const uint8_t RUN_TIME_SINCE_ENGINE_START      = 31;  // 0x1F - sec 
only returns in seconds which is not enough accuracy for my use case
is there any possible way to make the data coming in from the OBD II Scanner to be in milliseconds?

**Comment by PowerBroker2** [comment]
That PID as per the standard only goes down to the second and not lower. This can't be changed. You might, however, be able to interpolate using `millis()`...
